# Generated by Django 4.2.14 on 2024-08-02 18:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(1, 'CASH_ON_DELIVERY'), (3, 'BANK_TRANSFER'), (4, 'ONLINE_PAYMENT')], default=1)),
                ('shipping_method', models.PositiveSmallIntegerField(choices=[(1, 'UPS'), (2, 'DHL')], default=1)),
                ('order_price', models.PositiveIntegerField()),
                ('order_status', models.PositiveSmallIntegerField(choices=[(1, 'NEW'), (2, 'IN_PROGRESS'), (3, 'SHIPPED'), (4, 'DONE')], default=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='ecommerce.order')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_product', to='ecommerce.productvariation')),
            ],
        ),
    ]
