# Generated by Django 4.2.14 on 2024-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
