# Generated by Django 4.2.15 on 2024-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_productitem_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='discount',
            field=models.ManyToManyField(blank=True, related_name='discount', to='ecommerce.discount'),
        ),
    ]
