# Generated by Django 4.2.15 on 2024-08-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_productitem_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_checkout_id',
            new_name='stripe_session_id',
        ),
    ]
