# Generated by Django 4.2.10 on 2024-02-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_address_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='surname',
            new_name='last_name',
        ),
    ]
